# configuration for all branches

image: Visual Studio 2017

skip_tags: false

skip_branch_with_pr: true

test: off

# Skipping commits affecting specific files
skip_commits:
  files:
  - '**\AssemblyInfo*.*'
  - '**/*.md'
  - 'LICENSE'
  - dir/*
  - '.gitignore'
  - 'azure-pipelines.yml'

build:
  verbosity: minimal

environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - RUBY_VERSION: 24
  GitHubUserName:
    secure: 7OBtVAMTodMWK20wg6pGnQ==
  GitHubUserEmail:
    secure: /NpmL1KqwHyHFnF0GlUovA586wDIt8Hg/Q8Dro6kUpk=
  GitHubToken:
    secure: i/2hGsqVMwzdM5yIS4rxOIeG3ftx7su7klWYN80s/fHvgk7A5H2fF3oUTNLcyTbw
  GitRestAuth:
    secure: E3bCMe4LtDdAhHSYRcLp0N6DixJe1m8TNxhYeJW/GnqM3WXdRqsgkHSbwootPjJQtOQJrps4twmzTVzofLSVgPgbzU8PxU0AkJV7zwkyVOE=

init:
- git config --global core.autocrlf true
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubToken):x-oauth-basic@github.com`n"
- git config --global user.email "%GitHubUserEmail%"
- git config --global user.name "%GitHubUserName%"

install:
- set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
- bundle config --local path vendor/bundle
- gem install bundler --quiet --no-ri --no-rdoc
- gem install github_changelog_generator --quiet --no-ri --no-rdoc
- dotnet tool install --tool-path . nbgv
- ps: .\install-vsix-appveyor.ps1

before_build:
- ps: >-

    nuget restore source\nanoFramework.CoreLibrary.sln

    .\nbgv cloud -p source -a -c

build_script:
- ps: msbuild source\nanoFramework.CoreLibrary.sln /p:PublicRelease=true /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_deploy:
  - ps:  >-
      .\nbgv cloud --version=$env:NBGV_SemVer1

      $env:MyNuGetVersion = $env:NBGV_NuGetPackageVersion -replace "\-g$env:NBGV_GitCommitIdShort", " "
    
      .\generate-change-log.ps1

  - nuget pack source\nanoFramework.CoreLibrary.nuspec -Version %MyNuGetVersion%
  - nuget pack source\nanoFramework.CoreLibrary.DELIVERABLES.nuspec -Version %MyNuGetVersion%
  - ps:  >-
      .\commit-assemblyinfo-changes.ps1
      
      .\generate-change-log.ps1

      Push-AppveyorArtifact $env:APPVEYOR_BUILD_FOLDER\nanoFramework.CoreLibrary.$env:MyNuGetVersion.nupkg

after_deploy:
# for this environment variable to work here it has to be set in AppVeyor UI
- nuget push nanoFramework.CoreLibrary.%MyNuGetVersion%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package
- nuget push nanoFramework.CoreLibrary.DELIVERABLES.%MyNuGetVersion%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package

# requires APPVEYOR_DISCORD_WEBHOOK_URL enviroment variable set with Discord webhook URL
on_failure:
  - ps: |
  
      & $env:APPVEYOR_BUILD_FOLDER\appveyor-discord.ps1 failure $env:APPVEYOR_DISCORD_WEBHOOK_URL

on_success:
  - ps: .\update-dependencies.ps1

cache:
  - source\packages -> **source\packages.config

################################################
# override configuration for specific branches
for:

-
  branches:
    only:
      - master
      - /v\d.*/

  deploy:
  - provider: NuGet
    api_key: $(NuGetToken)
    skip_symbols: true
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    tag: v$(MyNuGetVersion)
    release: nanoFramework Base Class Library v$(MyNuGetVersion)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/master/CHANGELOG.md)\n\n## Install from NuGet\n\nThe following NuGet packages are available for download from this release\n\n:package: [.NET](https://www.nuget.org/packages/nanoFramework.CoreLibrary/$(MyNuGetVersion)) v$(MyNuGetVersion)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact:
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: false

-
  branches:
    only:
      - /dev(elop)?$/

  deploy:
  - provider: GitHub
    tag: v$(MyNuGetVersion)
    release: nanoFramework Core Library v$(MyNuGetVersion)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/develop/CHANGELOG.md)\n\n## Install from nanoFramework MyGet development feed\n\nThe following NuGet packages are available for download from this release\n\npackage: [.NET](https://www.myget.org/feed/nanoframework-dev/package/nuget/nanoFramework.CoreLibrary/$(MyNuGetVersion)) v$(MyNuGetVersion)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact: source\Nuget.CoreLibrary\bin\Release\nanoFramework.CoreLibrary.$(MyNuGetVersion).nupkg
    draft: true
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: false    

-
  branches:
    only:
      - /release.*/

  deploy:
  - provider: NuGet
    api_key: $(NuGetToken)
    skip_symbols: true
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    tag: v$(MyNuGetVersion)
    release: nanoFramework Core Library v$(MyNuGetVersion)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/$(appveyor_repo_branch)/CHANGELOG.md)\n\n## Install from NuGet\n\nThe following NuGet packages are available for download from this release\n\n:package: [.NET](https://www.nuget.org/packages/nanoFramework.CoreLibrary/$(MyNuGetVersion)) v$(MyNuGetVersion)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact:
    draft: true
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: false
