# configuration for "master" branch
-
  branches:
    only:
      - master

  image: Visual Studio 2017

  skip_branch_with_pr: true

  # Skipping commits affecting specific files
  skip_commits:
    files:
    - '**\AssemblyInfo.*'
    - '**/*.md'
    - 'LICENSE'
    - dir/*
    - '.gitignore'

  build:
    verbosity: minimal

  test: off

  environment:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    matrix:
      - RUBY_VERSION: 24
    GitHubUserName:
      secure: 7OBtVAMTodMWK20wg6pGnQ==
    GitHubUserEmail:
      secure: /NpmL1KqwHyHFnF0GlUovA586wDIt8Hg/Q8Dro6kUpk=
    GitHubToken:
      secure: i/2hGsqVMwzdM5yIS4rxOIeG3ftx7su7klWYN80s/fHvgk7A5H2fF3oUTNLcyTbw

  init:
    - git config --global core.autocrlf true
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubToken):x-oauth-basic@github.com`n"
    - git config --global user.email "%GitHubUserEmail%"
    - git config --global user.name "%GitHubUserName%"

  install:
    - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    - bundle config --local path vendor/bundle
    - gem install bundler --quiet --no-ri --no-rdoc
    - gem install github_changelog_generator --quiet --no-ri --no-rdoc
    - choco install gitversion.portable -pre -y
    - ps: .\install-vsix-appveyor.ps1

  before_build:
  - ps: >-

      nuget restore source\nanoFramework.CoreLibrary.sln

      C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo "source\System\AssemblyInfo2.cs"

  build_script:
  - ps: >-

      msbuild source\nanoFramework.CoreLibrary.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

      msbuild source\nanoFramework.CoreLibrary.Nuget.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  before_deploy:
    - ps:  >-

        # updated assembly info files

        git add "source\System\AssemblyInfo2.cs"

        git commit -m "Update assembly info file for v$env:GitVersion_NuGetVersionV2"

        "$(git push origin)"

        .\generate-change-log.ps1

  artifacts:
  - path: '**\bin\Release\*.nupkg'
    name: Nuget_Packages

  deploy:
  - provider: NuGet
    api_key:
      secure: NSRDXbS8tmzOy4wStGuO3yQMKI8Sk10vF8iQtz9ZDXEnHfwnuDdnXbr/Kno3MMvY
    skip_symbols: true
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    tag: v$(GitVersion_NuGetVersionV2)
    release: nanoFramework Core Library v$(gitversion_semver)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/master/CHANGELOG.md)\n\n## Install from NuGet\n\nThe following NuGet packages are available for download from this release\n\n:package: [.NET](https://www.nuget.org/packages/nanoFramework.CoreLibrary/$(GitVersion_NuGetVersionV2)) v$(GitVersion_NuGetVersionV2)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact: Nuget_Packages
    draft: true
    prerelease: true
    force_update: true

  # requires APPVEYOR_DISCORD_WEBHOOK_URL enviroment variable set with Discord webhook URL
  on_failure:
    - ps: |

          cd ..

          .\appveyor-discord.ps1 failure $env:APPVEYOR_DISCORD_WEBHOOK_URL

  cache:
    - source\packages -> **source\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml


####################################
# configuration for develop branches
-
  branches:
    only:
      - /dev.*/

  image: Visual Studio 2017

  skip_branch_with_pr: true

  skip_tags: false

  test: off
  
  pull_requests:
    do_not_increment_build_number: true

  # Skipping commits affecting specific files
  skip_commits:
    files:
    - '**\AssemblyInfo.*'
    - '**/*.md'
    - 'LICENSE'
    - dir/*
    - '.gitignore'

  build:
    verbosity: minimal

  environment:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    matrix:
      - RUBY_VERSION: 24
    GitHubUserName:
      secure: 7OBtVAMTodMWK20wg6pGnQ==
    GitHubUserEmail:
      secure: /NpmL1KqwHyHFnF0GlUovA586wDIt8Hg/Q8Dro6kUpk=
    GitHubToken:
      secure: i/2hGsqVMwzdM5yIS4rxOIeG3ftx7su7klWYN80s/fHvgk7A5H2fF3oUTNLcyTbw

  init:
    - git config --global core.autocrlf true
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubToken):x-oauth-basic@github.com`n"
    - git config --global user.email "%GitHubUserEmail%"
    - git config --global user.name "%GitHubUserName%"

  install:
    - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    - bundle config --local path vendor/bundle
    - gem install bundler --quiet --no-ri --no-rdoc
    - gem install github_changelog_generator --quiet --no-ri --no-rdoc
    - choco install gitversion.portable -pre -y
    - ps: .\install-vsix-appveyor.ps1

  before_build:
  - ps: >-

      nuget restore source\nanoFramework.CoreLibrary.sln

      C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo "source\System\AssemblyInfo2.cs"

  build_script:
  - ps: >-

      msbuild source\nanoFramework.CoreLibrary.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

      msbuild source\nanoFramework.CoreLibrary.Nuget.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  on_success:
  # for this environment variable to work here it has to be set in AppVeyor UI
  - nuget push source\Nuget.CoreLibrary\bin\Release\nanoFramework.CoreLibrary.%GitVersion_NuGetVersionV2%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package
  - nuget push source\Nuget.CoreLibrary.DELIVERABLES\bin\Release\nanoFramework.CoreLibrary.DELIVERABLES.%GitVersion_NuGetVersionV2%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package

  artifacts:
  - path: '**\bin\Release\*.nupkg'
    name: Nuget_Packages

  deploy:
  - provider: GitHub
    tag: v$(GitVersion_NuGetVersionV2)
    release: nanoFramework Core Library v$(gitversion_semver)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/develop/CHANGELOG.md)\n\n## Install from nanoFramework MyGet development feed\n\nThe following NuGet packages are available for download from this release\n\npackage: [.NET](https://www.myget.org/feed/nanoframework-dev/package/nuget/nanoFramework.CoreLibrary/$(GitVersion_NuGetVersionV2)) v$(GitVersion_NuGetVersionV2)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact: Nuget_Packages
    draft: true
    prerelease: true
    force_update: true

  before_deploy:
    - ps:  >-

        # updated assembly info files

        git add "source\System\AssemblyInfo2.cs"

        git commit -m "Update assembly info file for v$env:GitVersion_NuGetVersionV2"

        "$(git push origin)"

        .\generate-change-log.ps1

  # requires APPVEYOR_DISCORD_WEBHOOK_URL enviroment variable set with Discord webhook URL
  on_failure:
    - ps: |

          .\appveyor-discord.ps1 failure $env:APPVEYOR_DISCORD_WEBHOOK_URL

  cache:
    - source\packages -> **source\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml

############################################
# configuration for release candidate branch
-
  branches:
    only:
      - release.*

  image: Visual Studio 2017

  skip_branch_with_pr: true

  skip_tags: false

  # Skipping commits affecting specific files
  skip_commits:
    files:
    - '**\AssemblyInfo.*'
    - '**/*.md'
    - 'LICENSE'
    - dir/*
    - '.gitignore'

  build:
    verbosity: minimal

  test: off

  environment:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    matrix:
      - RUBY_VERSION: 24
    GitHubUserName:
      secure: 7OBtVAMTodMWK20wg6pGnQ==
    GitHubUserEmail:
      secure: /NpmL1KqwHyHFnF0GlUovA586wDIt8Hg/Q8Dro6kUpk=
    GitHubToken:
      secure: i/2hGsqVMwzdM5yIS4rxOIeG3ftx7su7klWYN80s/fHvgk7A5H2fF3oUTNLcyTbw

  init:
    - git config --global core.autocrlf true
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubToken):x-oauth-basic@github.com`n"
    - git config --global user.email "%GitHubUserEmail%"
    - git config --global user.name "%GitHubUserName%"

  install:
    - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    - bundle config --local path vendor/bundle
    - gem install bundler --quiet --no-ri --no-rdoc
    - gem install github_changelog_generator --quiet --no-ri --no-rdoc
    - choco install gitversion.portable -pre -y
    - ps: .\install-vsix-appveyor.ps1

  before_build:
  - ps: >-

      nuget restore source\nanoFramework.CoreLibrary.sln
        
      C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo "source\System\AssemblyInfo2.cs"

  build_script:
  - ps: >-

      msbuild source\nanoFramework.CoreLibrary.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

      msbuild source\nanoFramework.CoreLibrary.Nuget.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  on_success:
  # for this environment variable to work here it has to be set in AppVeyor UI
  - nuget push source\Nuget.CoreLibrary\bin\Release\nanoFramework.CoreLibrary.%GitVersion_NuGetVersionV2%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package
  - nuget push source\Nuget.CoreLibrary.DELIVERABLES\bin\Release\nanoFramework.CoreLibrary.DELIVERABLES.%GitVersion_NuGetVersionV2%.nupkg %MyGetToken% -Source https://www.myget.org/F/nanoframework-dev/api/v2/package

  artifacts:
  - path: '**\bin\Release\*.nupkg'
    name: Nuget_Packages

  deploy:
  - provider: GitHub
    tag: v$(GitVersion_NuGetVersionV2)
    release: nanoFramework Core Library v$(gitversion_semver)
    description: 'Check the [changelog](https://github.com/nanoframework/lib-CoreLibrary/blob/$(appveyor_repo_branch)/CHANGELOG.md)\n\n## Install from nanoFramework MyGet development feed\n\nThe following NuGet packages are available for download from this release\n\n:package: [.NET](https://www.myget.org/feed/nanoframework-dev/package/nuget/nanoFramework.CoreLibrary/$(GitVersion_NuGetVersionV2)) v$(GitVersion_NuGetVersionV2)'
    auth_token:
      secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
    artifact: Nuget_Packages
    draft: true
    prerelease: true
    force_update: true

  before_deploy:
    - ps:  >-

        # updated assembly info files

        git add "source\System\AssemblyInfo2.cs"

        git commit -m "Update assembly info file for v$env:GitVersion_NuGetVersionV2"

        "$(git push origin)"

        .\generate-change-log.ps1

  # requires APPVEYOR_DISCORD_WEBHOOK_URL enviroment variable set with Discord webhook URL
  on_failure:
    - ps: |

          .\appveyor-discord.ps1 failure $env:APPVEYOR_DISCORD_WEBHOOK_URL

  cache:
    - source\packages -> **source\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
